# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: en-US
title:  Uno's Blog
description: >- # this means to ignore newlines until "baseurl:"
  Programming issues and everyday thoughts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://djkeh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "djkeh/djkeh.github.io"
logo: /images/site-logo.png
date_format: "%Y-%m-%d"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: UA-57831105-1 # Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_site_verification: _-BmsjkTBBR4cNQjZMttIcsf0mmZw2fmNMhLozHdMrk # Google Search Console - information found in Settings > Ownership verification
disqus:
  shortname: djkeh # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Build settings
permalink: /:categories/:title/
markdown: kramdown
#theme: minima
remote_theme: "mmistakes/so-simple-theme"
feed:
  path: atom.xml
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Liquid
liquid:
  error_mode: strict

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
      sitemap: true

# Site Author
author:
  name: Uno Kim
  picture: /images/Uno-photo.jpg
  email: djkehh@gmail.com
  links:
    - title: Email
      url: mailto:djkehh@gmail.com
      icon: fas fa-envelope-square
    - title: Facebook
      url: https://www.facebook.com/djkehh
      icon: fab fa-facebook-square
    - title: Instagram
      url: https://instagram.com/djuno.pianoguy
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/djkeh
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Email
    url: mailto:djkehh@gmail.com
    icon: fas fa-envelope-square
  - title: Facebook
    url: https://www.facebook.com/djkehh
    icon: fab fa-facebook-square
  - title: Instagram
    url: https://instagram.com/djuno.pianoguy
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/djkeh
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# robots.txt setting
production: true
